### ISSUE TITLE
Feature request: Import wallet per mnemonic seed

### ISSUE THREAD

**Issue by cunum** [onbloc/adena-wallet#133]
Hi, I'm playing around with adena wallet atm, tried to import one of my keplr hot wallets but keplr only allows to export/view the mnemonic seed (not the private key) and adena only allows the import of private keys (not mnemonic seeds). 

So my feature request would be to also allow the import of a wallet by mnemonic seed to make it easier for keplr users to move their wallets to adena.

**Comment by dongwon8247** [comment]
Hi, we already support importing a wallet using the mnemonic seed. 

You can do that by clicking `Import Wallet` on the first page when you install it (Attached image), or if you have already made a wallet, you can go to `Settings` - `Security & Privacy` - `Reset Wallet` then you will be on the first page where you can import a wallet using the mnemonic seed.

![image](https://user-images.githubusercontent.com/74406335/235383484-112e71be-f372-4e0b-a411-cae349a5c202.png)

Hope this helps!

**Comment by cunum** [comment]
I see, thx for the info. On the first page I started with adding a Ledger account so I only had these options under "Add Account" to import my Keplr hot wallets afterwards:

<img width="351" alt="Bildschirm­foto 2023-05-01 um 02 34 11" src="https://user-images.githubusercontent.com/26085773/235383896-d5554236-a861-4e62-aa14-bcfa04f79a52.png">

Guess I'll do the Reset then and add the Ledger wallet after I do the mnemonic seed wallet import on the first page.
