### ISSUE TITLE
Max password length of 23

### ISSUE THREAD

**Issue by actuallymentor** [onbloc/adena-wallet#20]
Hello team,

I was wanting to play with the Adena wallet, but the max password length is 23:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/9071382/215316321-acc81665-2ffc-40cc-ad9e-b19545b64fe7.png">

From a security standpoint this is:

1. Not secure
2. Bad UX
3. Against guidelines (ie NIST)

From a programming perspective there is no reason not to make it a max of 128 or even 256 characters.

I recommend:

1. changing the maximum length to 256 characters
2. changing the minimum length to 8.

**Comment by dongwon8247** [comment]
Hi @actuallymentor, thank you for the issue.

We'll change the maximum length to 256 characters.

This kind of contribution is really helpful and appreciated.

If you have any issues while playing with Adena, please ping me!

Thanks.

**Comment by dongwon8247** [comment]
@actuallymentor Closing this issue as it's been solved. Thanks!
