### ISSUE TITLE
Programatic Access to Adena's version

### ISSUE THREAD

**Issue by ilgooz** [onbloc/adena-wallet#294]
The Gno IDE team finds it useful to be able to check Adena's version to ensure it meets the required minimum for the Playground. Is there a possibility to make this information available through the JS API?

cc @salmad3 @alexiscolin

**Comment by jinoosss** [comment]
Hi @ilgooz , 
I created a PR #295 based on that issue.

**Comment by dongwon8247** [comment]
Closed as completed in #295
