### ISSUE TITLE
[New Feature] Air-gap signing support

### ISSUE THREAD

**Issue by dongwon8247** [onbloc/adena-wallet#299]
See: https://github.com/gnolang/gno/issues/1375

**Comment by adr-sk** [comment]
Implemented in [v1.9.0](https://github.com/onbloc/adena-wallet/releases/tag/v1.9.0-rc.0).

- https://github.com/onbloc/adena-wallet/pull/330
- https://github.com/onbloc/adena-wallet/pull/331
