### ISSUE TITLE
Show current network on main page of the wallet

### ISSUE THREAD

**Issue by leohhhn** [onbloc/adena-wallet#303]
Hey @onbloc team, love the work on Adena. 

I found a small improvement that could be added to the Adena UI: having an indicator of what network you are currently connected to (ie staging/test3/.../mainnet) on the main page of the wallet. 

IMHO, this is an important piece of UI when using the wallet. What do you guys think?

**Comment by dongwon8247** [comment]
@leohhhn, thank you for suggesting this – it's a great idea. Maybe we can display the connected network on top of the main UI for all networks (staging/test3/...) except the mainnet. This would give a cleaner, more official UI to the mainnet, while still indicating clearly which network users are on when not on the mainnet.

**Comment by dongwon8247** [comment]
Closing as completed [#443](https://github.com/onbloc/adena-wallet/pull/443)
