### ISSUE TITLE
Error [security "connect-src" https]

### ISSUE THREAD

**Issue by sienrik15** [onbloc/adena-wallet#32]
Hi guys, Adena wallet show a Failed to load assets because has a https connections on localnetwork
Fixing asap, thanks
Adena Version 1.5.1
![image](https://user-images.githubusercontent.com/14026704/227064802-84165b17-2801-497e-8ae8-8e01905440f1.png)

**Comment by r3v4s** [comment]
Close Issue, due to fix by #33
