### ISSUE TITLE
Bug: Unable to add new account to existing wallet

### ISSUE THREAD

**Issue by leohhhn** [onbloc/adena-wallet#437]
Hey, I tried adding a new wallet address in the newest version of Adena - 1.9.1.

When I click "Add account" in the left bar, I get a new tab opened that is fully white and doesn't respond. I am using Arc Browser on MacOS. Below are the screenshots.

Add Account:
![Screenshot 2024-03-08 at 22 38 42](https://github.com/onbloc/adena-wallet/assets/33522493/f2b6b961-7dd6-460c-812a-94dee9d1cc04)

Screen after clicking "Add Account":
![Screenshot 2024-03-08 at 22 37 56](https://github.com/onbloc/adena-wallet/assets/33522493/3175ff41-ecda-49b6-a000-c3fc02322755)

Nothing happens after some time, and it seems I'm unable to add a new account.

**Comment by dongwon8247** [comment]
@leohhhn We will look into this. Thank you for reporting.
