### ISSUE TITLE
Bug: sometimes extension is unresponsive

### ISSUE THREAD

**Issue by x1unix** [onbloc/adena-wallet#496]
Sometimes, the extension stops responding and at the same time when I'm trying to change network - I get an empty popup.

In addition to blank dialog popups, Adena Wallet extension button also doesn't work.
Disabling and re-enabling extension doesn't work. The only was to fix the issue is to terminate and restart Chrome process.

Reproducing is quite problematic, but it occurs more often when wallet is locked or when page is frequently reloaded.

https://github.com/onbloc/adena-wallet/assets/9203548/a5bde992-468b-40af-9a04-a3f3929b4a46

**Comment by x1unix** [comment]
Found a new pattern - extension stops working right after DevTools is opened.



https://github.com/onbloc/adena-wallet/assets/9203548/843c692e-2372-41a9-9fc6-69d15388aa76

**Comment by adr-sk** [comment]
https://github.com/onbloc/adena-wallet/assets/105615982/3d807836-ec9c-4e83-a73e-170b9a345a1a

Hi @x1unix , thank you for the report. Unfortunately, we cannot seem to replicate the issue on our end, neither on Mac nor Windows.

Can you please confirm that:
1. You're using the latest version of Adena.
2. There's no other Adena Extension installed on your current Chrome Profile? (ones that you've locally built)

Also, can you please check if you can replicate the issue on any other devices you own? Thank you.

**Comment by x1unix** [comment]
@adr-sk thanks for a reply.

> You're using the latest version of Adena.

I'm using Adena 1.10.2 on Chrome 124.0.6367.207. That's the version that was available in Chrome store.

> There's no other Adena Extension installed on your current Chrome Profile (ones that you've locally built)

I don't have Adena installed in other profiles.

> Also, can you please check if you can replicate the issue on any other devices you own? Thank you.

Checked on Arc browser and Chrome beta - can't reproduce.

**Comment by x1unix** [comment]
Probably a config issue, closing this ticket until this will appear again on a new fresh installation.
