### ISSUE TITLE
request: adding accounts with mnemonics (after first use)

### ISSUE THREAD

**Issue by thehowl** [onbloc/adena-wallet#507]
Hey, I noticed you can only currently import accounts using private keys, if you try to do it after Adena already has an account.

Can we add support for mnemonic import? This way we can have own keys + keys like test1.

Thanks!

**Comment by adr-sk** [comment]
Hey @thehowl , this feature will be supported in the future. We're planning to provide an intuitive multi seed phrase management UX. We'll keep this issue open until it's added.

In the meantime, you can import the Gno test account using its private key which was added to the docs in this PR: https://github.com/gnolang/gno/pull/1990
