### ISSUE TITLE
[REQUEST] Delete custom tokens 

### ISSUE THREAD

**Issue by miguelito766** [onbloc/adena-wallet#528]
Hello guys,

As user i would like to delete some tests tokens to keep my interface clean.

We can deactivate it i saw but it would be nice to delete aswell

Not urgent :)

![image](https://github.com/onbloc/adena-wallet/assets/7680472/64c76c7c-8943-484f-9c2e-688c88d818a0)
![image](https://github.com/onbloc/adena-wallet/assets/7680472/ecd6d349-e588-4ca8-9fc5-67f16eda554a)

**Comment by dongwon8247** [comment]
@miguelito766 Hey, wouldn't it be enough if you can just disable them in the `Manage Tokens` menu?

**Comment by dongwon8247** [comment]
I think the best UX for this is:
1. By default, Adena catches and shows all tokens that the account has a balance in
2. User can disable them in Manage Token (having the balance in +100 tokens is not a usual case here, I think. you'd probably want to separate it into many accounts)
3. If User wants to add the tokens that they don't have balance in, then they can add them by searching it or with `path` manually from the `+` page inside `Manage Token`.

**Comment by miguelito766** [comment]
sounds good
